spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/playground-qa
    username: ${dbusername}
    password: ${dbpassword}
    initialization-mode: always
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_HOST_PORT:8500}
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_HOST_PORT:8200}
      scheme: http
      authentication: TOKEN
      token: ${VAULT_TOKEN:playground-secret}
      kv-version: 2
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_HOST_PORT:6379}         