spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/playground-qa
    username: ${dbusername}
    password: ${dbpassword}
    initialization-mode: always
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_HOST_PORT:8500}
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: s.yy0MQMIUu6aOfqAv8kOa4pZ6
      kv-version: 2     